name: Validate
description: Validate Go code (build + lint)
runs:
  using: composite
  steps:
    - name: Go build
      run: go build ./...
      shell: bash

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: latest
