name: Deploy staging
on:
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize, edited, reopened ]
concurrency:
  group: build-release-version
  cancel-in-progress: false
permissions:
  issues: write
  contents: write
  pull-requests: write

env:
  TF_VAR_env: staging
  TF_VAR_zone_id: ${{ secrets.ZONE_ID }}
  TF_VAR_root_domain: foam-app.com
  TF_VAR_private_key: ${{ secrets.STAGING_PRIVATE_KEY }}
  TF_VAR_certificate_body: ${{ secrets.STAGING_CERTIFICATE_BODY }}
  TF_VAR_certificate_chain: ${{ secrets.CERTIFICATE_CHAIN }}
  TF_VAR_deployed_by: ${{ github.actor }}
  TF_VAR_git_sha: ${{ github.sha }}

jobs:
  release:
    name: Deploy staging
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Load secrets
        id: load_secrets
        uses: 1password/load-secrets-action@v3
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          APP_TWITCH_CLIENT_ID: op://ci-cd/foam-proxy-staging/APP_TWITCH_CLIENT_ID
          APP_TWITCH_CLIENT_SECRET: op://ci-cd/foam-proxy-staging/APP_TWITCH_CLIENT_SECRET
          MENUBAR_TWITCH_CLIENT_ID: op://ci-cd/foam-proxy-staging/MENUBAR_TWITCH_CLIENT_ID
          MENUBAR_TWITCH_CLIENT_SECRET: op://ci-cd/foam-proxy-staging/MENUBAR_TWITCH_CLIENT_SECRET
          PROXY_DSN: op://ci-cd/foam-proxy-staging/SENTRY_PROXY_DSN
          AUTHORIZER_DSN: op://ci-cd/foam-proxy-staging/SENTRY_AUTH_DSN
          PUSHGATEWAY_URL: op://ci-cd/foam-proxy-staging/PUSHGATEWAY_URL
          PUSHGATEWAY_AUTH_HEADER: op://ci-cd/foam-proxy-staging/PUSHGATEWAY_AUTH_HEADER
          API_KEY: op://ci-cd/foam-proxy-staging/API_KEY
          OP_ENV_FILE: ".env"

      - name: Set Terraform variables
        run: |
          echo "TF_VAR_app_twitch_client_id=$APP_TWITCH_CLIENT_ID" >> $GITHUB_ENV
          echo "TF_VAR_app_twitch_client_secret=$APP_TWITCH_CLIENT_SECRET" >> $GITHUB_ENV
          echo "TF_VAR_menubar_twitch_client_id=$MENUBAR_TWITCH_CLIENT_ID" >> $GITHUB_ENV
          echo "TF_VAR_menubar_twitch_client_secret=$MENUBAR_TWITCH_CLIENT_SECRET" >> $GITHUB_ENV
          echo "TF_VAR_proxy_dsn=$PROXY_DSN" >> $GITHUB_ENV
          echo "TF_VAR_authorizer_dsn=$AUTHORIZER_DSN" >> $GITHUB_ENV
          echo "TF_VAR_pushgateway_url=$PUSHGATEWAY_URL" >> $GITHUB_ENV
          echo "TF_VAR_pushgateway_auth_header=$PUSHGATEWAY_AUTH_HEADER" >> $GITHUB_ENV
          echo "TF_VAR_api_key=$API_KEY" >> $GITHUB_ENV

      - name: Install
        uses: ./.github/actions/install

      - name: Validate
        uses: ./.github/actions/validate

      - name: Build lambdas
        uses: ./.github/actions/build

      - name: Deploy
        uses: ./.github/actions/deploy
        with:
          environment: staging
          aws-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
